apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/silente/Apps/Kube/kompose/kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: angular
status:
  loadBalancer: {}
